package com.core.bean;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TResource generated by hbm2java
 */
@Entity
@Table(name = "t_resource", catalog = "mvc")
public class Resource extends BaseEntity {

	private static final long serialVersionUID = 1L;
	
	private String resourceType;
	private String resourceName;
	private String resourceDesc;
	private String resourcePath;
	private Integer resourcePriority;
	
	@Column(name = "RESOURCE_TYPE", nullable = false, length = 10)
	public String getResourceType() {
		return this.resourceType;
	}

	public void setResourceType(String resourceType) {
		this.resourceType = resourceType;
	}

	@Column(name = "RESOURCE_NAME", nullable = false, length = 50)
	public String getResourceName() {
		return this.resourceName;
	}

	public void setResourceName(String resourceName) {
		this.resourceName = resourceName;
	}

	@Column(name = "RESOURCE_DESC", length = 200)
	public String getResourceDesc() {
		return this.resourceDesc;
	}

	public void setResourceDesc(String resourceDesc) {
		this.resourceDesc = resourceDesc;
	}

	@Column(name = "RESOURCE_PATH", nullable = false, length = 200)
	public String getResourcePath() {
		return this.resourcePath;
	}

	public void setResourcePath(String resourcePath) {
		this.resourcePath = resourcePath;
	}

	@Column(name = "RESOURCE_PRIORITY", precision = 8, scale = 0)
	public Integer getResourcePriority() {
		return this.resourcePriority;
	}

	public void setResourcePriority(Integer resourcePriority) {
		this.resourcePriority = resourcePriority;
	}

}
