package com.core.bean;

// Generated 2015-3-26 18:29:10 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TRole generated by hbm2java
 */
@Entity
@Table(name = "t_role", catalog = "mvc")
public class Role extends BaseEntity {

	private static final long serialVersionUID = 1L;
	
	private String roleName;
	private String roleDesc;

	@Column(name = "ROLE_NAME", nullable = false, length = 36)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "ROLE_DESC", length = 100)
	public String getRoleDesc() {
		return this.roleDesc;
	}

	public void setRoleDesc(String roleDesc) {
		this.roleDesc = roleDesc;
	}

}
